### PR TITLE
Use seconds from the FetchCompletedTime for LastModified time

### PR DESCRIPTION
**Pull request by phanidv**
`LastModified` field in the `FetchHistory` table is expected to be in _seconds_, but sometimes is stored in _millis_ causing the parsing logic to give a date in the future when retrieved. This is because the `FetchCompletedTime` is set in _millis_ and that is used if the `A_LAST_MODIFIED_HEADER` is missing for a `CrawlUri`

### CODE REVIEW

**Comment by anjackson** [comment]
Thanks!

**Comment by anjackson** [comment]
Ah, sorry, I merged that by mistake. I'm not sure of the status of the HBase classes.

**Comment by anjackson** [comment]
In case it help, after merging this we saw these build errors:

```
Error:  Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.016 s <<< FAILURE! - in org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest
Error:  itPutsLastModifiedHeaderIfPresent(org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest)  Time elapsed: 0.01 s  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest.itPutsLastModifiedHeaderIfPresent(MultiColumnRecrawlDataSchemaTest.java:39)
Caused by: java.lang.RuntimeException: Unexpected version format: 17.0.6
	at org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest.itPutsLastModifiedHeaderIfPresent(MultiColumnRecrawlDataSchemaTest.java:39)

Error:  itPutsCrawlFetchedTimeIfLastModifiedHeaderIsMissing(org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest)  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.client.Put
	at org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest.itPutsCrawlFetchedTimeIfLastModifiedHeaderIsMissing(MultiColumnRecrawlDataSchemaTest.java:58)

Error:  itSkipsLastModifiedIfBothHeaderAndFetchCompletedTimeAreMissing(org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.client.Put
	at org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest.itSkipsLastModifiedIfBothHeaderAndFetchCompletedTimeAreMissing(MultiColumnRecrawlDataSchemaTest.java:65)

Error:  itPutsCrawlFetchedTimeIfLastModifiedHeaderIsNull(org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest)  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.client.Put
	at org.archive.modules.recrawl.hbase.MultiColumnRecrawlDataSchemaTest.itPutsCrawlFetchedTimeIfLastModifiedHeaderIsNull(MultiColumnRecrawlDataSchemaTest.java:49)

[INFO] Running org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest
Error:  Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest
Error:  itPutsLastModifiedHeaderIfPresent(org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.client.Put
	at org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest.itPutsLastModifiedHeaderIfPresent(SingleColumnJsonRecrawlDataSchemaTest.java:40)

Error:  itPutsCrawlFetchedTimeIfLastModifiedHeaderIsMissing(org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.client.Put
	at org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest.itPutsCrawlFetchedTimeIfLastModifiedHeaderIsMissing(SingleColumnJsonRecrawlDataSchemaTest.java:61)

Error:  itSkipsLastModifiedIfBothHeaderAndFetchCompletedTimeAreMissing(org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.client.Put
	at org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest.itSkipsLastModifiedIfBothHeaderAndFetchCompletedTimeAreMissing(SingleColumnJsonRecrawlDataSchemaTest.java:69)

Error:  itPutsCrawlFetchedTimeIfLastModifiedHeaderIsNull(org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest)  Time elapsed: 0 s  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.hbase.client.Put
	at org.archive.modules.recrawl.hbase.SingleColumnJsonRecrawlDataSchemaTest.itPutsCrawlFetchedTimeIfLastModifiedHeaderIsNull(SingleColumnJsonRecrawlDataSchemaTest.java:51)
```
